// import img_01 from '/img_01.jpg'

export const ItemsList = [
  {
    id: 0,
    location: "Piazza delle Murate - Firenze",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_01.jpg",
    path: "/",
  },
  {
    id: 1,
    location: "Scuola di cucina - Mercato Centrale Firenze",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_02.jpg",
    path: "/",
  },
  {
    id: 2,
    location: "Palazzo Vecchio - Firenze",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_03.jpg",
    path: "/",
  },
  {
    id: 3,
    location: "Barcelona Airport",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_04.jpg",
    path: "/",
  },
  {
    id: 4,
    location: "Barcelona Airport",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_01.jpg",
    path: "/",
  },
  {
    id: 5,
    location: "Barcelona Airport",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_02.jpg",
    path: "/",
  },
  {
    id: 6,
    location: "Sant Jordi 2023 - Barcelona",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_03.jpg",
    path: "/",
  },
  {
    id: 7,
    location: "Sant Jordi 2023 - Barcelona",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_04.jpg",
    path: "/",
  },
  {
    id: 8,
    location: "Sant Jordi 2023 - Barcelona",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_01.jpg",
    path: "/",
  },
  {
    id: 9,
    location: "Biblioteca Gabriel García Márquez - Barcelona",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_02.jpg",
    path: "/",
  },
  {
    id: 9,
    location: "Biblioteca Gabriel García Márquez - Barcelona",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_03.jpg",
    path: "/",
  },
  {
    id: 10,
    location: "Biblioteca Gabriel García Márquez - Barcelona",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_04.jpg",
    path: "/",
  },
  {
    id: 11,
    location: "Biblioteca Gabriel García Márquez - Barcelona",
    camera: "Olympus OM-10",
    measures: "24 x 36cm",
    price: 50,
    image: "/images/img_01.jpg",
    path: "/",
  },
];
